version: "3.4"
services:
  users-pg:
    container_name: users-pg
    image: postgres:15
    restart: always
    user: postgres
    hostname: "${USER_DB_HOSTNAME}"
    ports:
      - "${USER_DB_PORT}:${USER_DB_PORT}"
    volumes:
      - type: volume
        source: pg-users-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres-users/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      PGPORT: "${USER_DB_PORT}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3

  parcel-pg:
    container_name: parcel-pg
    image: postgres:15
    restart: always
    user: postgres
    hostname: "${PARCEL_DB_HOSTNAME}"
    ports:
      - "${PARCEL_DB_PORT}:${PARCEL_DB_PORT}"
    volumes:
      - type: volume
        source: pg-parcels-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres-parcels/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      PGPORT: "${PARCEL_DB_PORT}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3

  parcel-discovery:
    container_name: parcel-discovery
    build: ../discovery/.
    restart: always
    ports:
      - "${DISCOVERY_PORT}:${DISCOVERY_PORT}"
    environment:
      PORT: "${DISCOVERY_PORT}"
      HOSTNAME: "${DISCOVERY_HOSTNAME}"

  gateway:
    container_name: parcel-gateway
    build: ../gateway/.
    restart: always
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      DISCOVERY_URL: "http://${DISCOVERY_HOSTNAME}:${DISCOVERY_PORT}/eureka/"
      JWT_RSA_PUBLIC_KEY_PATH: "${JWT_RSA_PUBLIC_KEY_PATH}"
    volumes:
      - type: bind
        source: ./jwtRS256.key.pub
        target: "${JWT_RSA_PUBLIC_KEY_PATH}"

  user-service:
    container_name: user-service
    build: ../user-service/.
    restart: always
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      DISCOVERY_URL: "http://${DISCOVERY_HOSTNAME}:${DISCOVERY_PORT}/eureka/"
      JWT_RSA_PRIVATE_KEY_PATH: "${JWT_RSA_PRIVATE_KEY_PATH}"
      DB_URL: "jdbc:postgresql://${USER_DB_HOSTNAME}:${USER_DB_PORT}/userdb"
      DB_USERNAME: "${USER_DB_USER}"
      DB_PASSWORD: "${USER_DB_PASSWORD}"
      JWT_TOKEN_EXPIRY_MS: "${JWT_TOKEN_EXPIRY_MS}"
    volumes:
      - type: bind
        source: ./jwtRS256.key
        target: "${JWT_RSA_PRIVATE_KEY_PATH}"

volumes:
  pg-users-data:
  pg-parcels-data: